name: sairdriver
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_storage: ^11.7.1
  cloud_firestore: ^4.16.1
  firebase_auth: ^4.2.0
  provider: ^6.1.2
  firebase_app_check: ^0.2.2+7
  firebase_core: 2.32.0
  persistent_bottom_nav_bar: ^6.2.1
  animated_splash_screen: ^1.3.0
  google_maps_flutter: ^2.9.0
  flutter_riverpod: ^2.5.3
  board_datetime_picker: ^2.1.4
  hugeicons: ^0.0.7



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  google_fonts: ^6.2.1
  awesome_snackbar_content: ^0.1.4
  font_awesome_flutter: ^10.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/image/
    - assets/image/greenMapMarker.png
    - assets/image/SGreenCircularPattern.png