name: sairdriver
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_storage: ^11.7.1
  cloud_firestore: ^4.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  firebase_core: 2.32.0
  flutter_lints: ^5.0.0
  google_fonts: ^6.2.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/image/